// Design tokens copied exactly from the Stitch AI export — see
// hulurent-docs' ARCHITECTURE.md §4 for where this fits, and don't
// hand-edit color/font/spacing values here without updating the
// Stitch source too, so the two don't drift apart.

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9fa',
        'primary-fixed-dim': '#8fd1d9',
        tertiary: '#56340e',
        'surface-dim': '#d9dadb',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#623f18',
        'on-surface': '#191c1d',
        'outline-variant': '#bfc8c9',
        'on-tertiary-container': '#f1bd8b',
        'on-secondary-fixed': '#171b2b',
        'secondary-fixed': '#dee1f8',
        'surface-container': '#edeeef',
        'surface-container-low': '#f3f4f5',
        background: '#f8f9fa',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#f0f1f2',
        'surface-container-high': '#e7e8e9',
        'secondary-fixed-dim': '#c2c5db',
        'on-primary-container': '#90d2da',
        primary: '#004349',
        secondary: '#5a5d70',
        'surface-tint': '#20686f',
        'on-tertiary-fixed': '#2c1600',
        'on-primary-fixed': '#002023',
        'primary-fixed': '#abeef6',
        outline: '#6f797a',
        'error-container': '#ffdad6',
        'on-secondary-container': '#606376',
        'surface-variant': '#e1e3e4',
        'inverse-primary': '#8fd1d9',
        'on-secondary-fixed-variant': '#424658',
        'on-secondary': '#ffffff',
        'tertiary-container': '#704b23',
        'tertiary-fixed-dim': '#f0bd8b',
        'on-surface-variant': '#3f484a',
        error: '#ba1a1a',
        'on-background': '#191c1d',
        'inverse-surface': '#2e3132',
        'tertiary-fixed': '#ffdcbd',
        'on-primary-fixed-variant': '#004f55',
        'secondary-container': '#dee1f8',
        'on-tertiary': '#ffffff',
        'primary-container': '#0d5c63',
        'on-primary': '#ffffff',
        'surface-bright': '#f8f9fa',
        'surface-container-highest': '#e1e3e4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        gutter: '24px',
        'margin-desktop': '40px',
        base: '8px',
        'stack-lg': '24px',
        'stack-sm': '4px',
        'stack-md': '12px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter'],
        'display-lg': ['Inter'],
        'label-sm': ['Inter'],
        'display-lg-mobile': ['Inter'],
        'body-lg': ['Inter'],
        'headline-md': ['Inter'],
        'price-display': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg': ['Inter'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'price-display': ['20px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      boxShadow: {
        subtle: '0 1px 2px 0 rgb(0 0 0 / 0.06)',
        hover: '0 4px 12px 0 rgb(0 0 0 / 0.10)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};